@@PORT@@ = VideoCamera()
@@PORT@@.translate(x = @@X@@, y = @@Y@@, z = @@Z@@)
@@PORT@@.properties(cam_width=20)
@@PORT@@.properties(cam_height=20)
@@PORT@@.properties(cam_far=2)
@@PORT@@.properties(cam_focal=31)
@@PORT@@.add_interface('socket')
robot.append(@@PORT@@)